/* Generated By:JavaCC: Do not edit this line. WordTokenizerConstants.java */
package net.sf.okapi.steps.tokenization.engine.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface WordTokenizerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int HYPHENATED = 1;
  /** RegularExpression Id. */
  int ALPHANUM = 2;
  /** RegularExpression Id. */
  int APOSTROPHE = 3;
  /** RegularExpression Id. */
  int ACRONYM = 4;
  /** RegularExpression Id. */
  int COMPANY = 5;
  /** RegularExpression Id. */
  int EMAIL = 6;
  /** RegularExpression Id. */
  int HOST = 7;
  /** RegularExpression Id. */
  int NUM = 8;
  /** RegularExpression Id. */
  int P = 9;
  /** RegularExpression Id. */
  int HAS_DIGIT = 10;
  /** RegularExpression Id. */
  int ALPHA = 11;
  /** RegularExpression Id. */
  int LETTER = 12;
  /** RegularExpression Id. */
  int DIGIT = 13;
  /** RegularExpression Id. */
  int NOISE = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<HYPHENATED>",
    "<ALPHANUM>",
    "<APOSTROPHE>",
    "<ACRONYM>",
    "<COMPANY>",
    "<EMAIL>",
    "<HOST>",
    "<NUM>",
    "<P>",
    "<HAS_DIGIT>",
    "<ALPHA>",
    "<LETTER>",
    "<DIGIT>",
    "<NOISE>",
  };

}
