/* Generated By:JavaCC: Do not edit this line. SimplifierRulesConstants.java */
package net.sf.okapi.core.simplifierrules;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimplifierRulesConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int RULE_START = 7;
  /** RegularExpression Id. */
  int RULE_END = 8;
  /** RegularExpression Id. */
  int DATA = 9;
  /** RegularExpression Id. */
  int OUTER_DATA = 10;
  /** RegularExpression Id. */
  int ORIGINAL_ID = 11;
  /** RegularExpression Id. */
  int TYPE = 12;
  /** RegularExpression Id. */
  int TAG_TYPE = 13;
  /** RegularExpression Id. */
  int CLOSING = 14;
  /** RegularExpression Id. */
  int OPENING = 15;
  /** RegularExpression Id. */
  int STANDALONE = 16;
  /** RegularExpression Id. */
  int ADDABLE = 17;
  /** RegularExpression Id. */
  int DELETABLE = 18;
  /** RegularExpression Id. */
  int CLONEABLE = 19;
  /** RegularExpression Id. */
  int OR = 20;
  /** RegularExpression Id. */
  int AND = 21;
  /** RegularExpression Id. */
  int LPAREN = 22;
  /** RegularExpression Id. */
  int RPAREN = 23;
  /** RegularExpression Id. */
  int EQUAL = 24;
  /** RegularExpression Id. */
  int MATCH = 25;
  /** RegularExpression Id. */
  int NOT_EQUAL = 26;
  /** RegularExpression Id. */
  int NOT_MATCH = 27;
  /** RegularExpression Id. */
  int QUOTE_DOUBLE = 28;
  /** RegularExpression Id. */
  int STRING_DOUBLE_EMPTY = 29;
  /** RegularExpression Id. */
  int STRING_DOUBLE_BODY = 30;
  /** RegularExpression Id. */
  int STRING_DOUBLE_NONEMPTY = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"if\"",
    "\";\"",
    "\"DATA\"",
    "\"OUTER_DATA\"",
    "\"ORIGINAL_ID\"",
    "\"TYPE\"",
    "\"TAG_TYPE\"",
    "\"CLOSING\"",
    "\"OPENING\"",
    "\"STANDALONE\"",
    "\"ADDABLE\"",
    "\"DELETABLE\"",
    "\"CLONEABLE\"",
    "\"or\"",
    "\"and\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"~\"",
    "\"!=\"",
    "\"!~\"",
    "\"\\\"\"",
    "\"\\\"\\\"\"",
    "<STRING_DOUBLE_BODY>",
    "<STRING_DOUBLE_NONEMPTY>",
  };

}
